### ISSUE TITLE
xml.parsers.expat.ExpatError: no element found

### ISSUE THREAD

**Issue by KubilayC38** [Luis-Hebendanz/strawpoll-voting-bot#8]
If I want to use the tool I just get this error message:
`Traceback (most recent call last):
  File "Main.py", line 250, in <module>
    Main()
  File "Main.py", line 105, in __init__
    xmldoc = minidom.parse(self.proxyListFile)
  File "/usr/lib/python3.6/xml/dom/minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 211, in parseFile
    parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 304, column 0`

I use Python 3.6.7 and pip 19.0.3. 

I have really no idea what I could do now. Could someone help me?

**Comment by 0x006E** [comment]
Its most likely an error due to the XMLParser not able to parse the ProxyListFile. Even if you could do that, I would say of that most of the proxies in that list will not work as the developer is inactive (they are very old proxies)
